name: Addition Request
description: Propose a new resource
labels: ["documentation", "enhancement"]
body:
  - type: dropdown
    validations:
        required: true
    attributes:
      label: Category
      multiple: false
      options:
        - Dataset
        - Model
        - System
        - Book
        - Survey
        - Course
        - Talk
        - Conference or Workshop
        - Other (please specify below)
  
  - type: textarea
    validations:
        required: true
    attributes:
      label: Description
      description: A clear and detailed description of the proposed resource
      placeholder: |
        Please describe the new resource in detail. 
        If you are proposing a new dataset, please include the following information: task, domain, language, size, links to paper/code/data, and any other relevant information.
        If you are proposing a new model, please include the following information: type, language, size, links to paper/code/checkpoints, and any other relevant information.
