name: Documentation Fixes
description: Tell us about how we can improve our documentation
labels: ["documentation", "invalid"]
body:
  - type: textarea
    validations:
        required: true
    attributes:
      label: 📚 Documentation
      description: A clear description of the mistake in the documentation
      placeholder: |
        Please describe any typos or mistakes you found in our list.
